# Header
menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
rss: /atom.xml
index_img: /images/topimg.jpg
archive_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/archive.jpg
tag_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/category.jpg
tag_per_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/category.jpg
category_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/tag.png
category_per_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/tag.png

# 這個選項是用來顯示文章的相關信息的。
post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字
# 為你的博客文章展示文章版權和許可協議
post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  author: xxxx
  copyright_author_href: https://xxxxxx.com
  copyright_url: https://xxxxxx.com
  copyright_info: 此文章版權歸xxxxx所有，如有轉載，請註明來自原作者
# 相關文章推薦的原理是根據文章tags的比重來推薦
related_post:
  enable: true
  limit: 3 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日
# 開啟文章錨點後，當你在文章頁進行滾動時，文章鏈接會根據標題ID進行替換
# (注意: 每替換一次，會留下一個歷史記錄。所以如果一篇文章有很多錨點的話，網頁的歷史記錄會很多。)
anchor: true
# 可開啟圖片Figcaption描述文字顯示
photofigcaption: true
# 可配置網站是否可以複製、複製的內容是否添加版權信息
copy:
  enable: true #是否開啟網站複製權限
  copyright: #複製的內容後面加上版權信息
    enable: false #是否開啟複製版權信息添加
    limit_count: 50 #字數限制，當複製文字大於這個字數限制時，將在複製的內容後面加上版權信息

# 簡體繁體互換, 右下角會有簡繁轉換按鈕。
translate:
  enable: true
  # 默認按鈕顯示文字(網站是簡體，應設置為'default: 繁',反之则是 簡)
  default: 繁
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 2
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: "繁"
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: "簡"
# 可以改變字體大小（最小隻能到 10px，最大隻能到 20px）
change_font_size: true
# 訪問人數 busuanzi (UV 和 PV)
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true
# 網頁已運行時間
runtimeshow:
  enable: true
  publish_date: 2021/12/20 00:00:00
# 分享
sharejs:
  enable: false
  item: wechat # facebook,twitter,wechat,weibo,qq
# 背景特效
canvas_nest:
  enable: true
  color: "0,0,255" #线条颜色, 默认值: '0,0,0'; RGB 值：（R、G、B）。（注意：使用“,”分隔。）
  opacity: 0.7 # 线条的不透明度（0~1），默认：0.5。
  zIndex: -1 # 背景的 z-index 属性，默认值：-1。
  count: 99 # 行数，默认：99。
  mobile: false # false 手机端不显示 true 手机端显示
# 点击出现爱心
click_heart:
  enable: true
  mobile: false
# 美化页面显示
beautify:
  enable: true
  field: site # site/post ; post:只在文章页生效,site:在全站生效
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"
# 主页副标题
subtitle:
  enable: true
  # 打字效果
  effect: true
  # 循环或者只打字一次
  loop: false
  # source调用第三方服务
  # source: false 关闭调用
  # source: 1  调用搏天api的随机语录（简体）
  # source: 2  调用一言网的一句话（简体）
  # source: 3  调用一句网（简体）
  # source: 4  调用今日诗词（简体
  # subtitle 会先显示 source , 再显示 sub 的内容
  source: false
  # 如果有英文逗号' , ',请使用转义字元 &#44;
  # 如果有英文双引号' " ',请使用转义字元 &quot;
  # 开头不允许转义字元，如需要，请把整个句子用双引号包住
  # 例如 ”&quotNever put off till tomorrow what you can do today&quot"
  # 如果关闭打字效果，subtitle只会显示sub的第一行文字
  sub:
    - 今日事&#44;今日毕
    - Never put off till tomorrow what you can do today
# 主页设置
# 默认top_img全屏，site_info在中间
# 使用默认, 都无需填写（建议默认）
index_site_info_top: # 主页标题距离顶部距离  例如 300px/300em/300rem/10%
index_top_img_height: 400px #主页top_img高度 例如 300px/300em/300rem  不能使用百分比
# 加载动画 Loading Animation
preloader: true
# Snackbar 弹窗
# https://github.com/polonel/SnackBar
# position 弹窗位置
# 可选 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: bottom-left
  bg_light: "#49b1f5" #light mode时弹窗背景
  bg_dark: "#2d3035" #dark mode时弹窗背景
# prefetch (预加载) 当鼠标悬停到链接上超过 65 毫秒时，Instantpage 会对该链接进行预加载，可以提升访问速度。
instantpage: true

# 侧边排版
aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: false
	    icon: fab fa-github
      text: Github
      link: https://github.com/jerryc127/hexo-theme-butterfly
  card_announcement: ## 公告
    enable: true
    content: 如果我写的不好，那就先忍着~
  card_categories:  ## 分类
    enable: true
    limit: 2 # 如果设置 0 将显示所有
    expand: none # none/true/false
  card_tags:      ## 标签
    enable: true
    limit: 40 # 如果设置 0 将显示所有
    color: true 
  card_recent_post:  ## 最新文章
    enable: true
    limit: 5 # 如果设置 0 将显示所有
  card_archives:  ## 归档
    enable: true
    type: monthly # 每年或每月
    format: YYYY年MM月 # eg: YYYY年MM月 MMMM YYYY
    order: -1 # 排序。 1、asc为升序； -1, desc 降序
    limit: 5 # 如果设置 0 将显示所有
  card_webinfo: true ## 网站信息

# Content
excerpt_link: Read More
fancybox: true
index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config
avatar:
  img: /images/avatar.jpg
  effect: false # 頭像會一直轉圈

# Sidebar
sidebar: right
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: "monthly"
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /images/avatar-modified.png
twitter:
google_plus:
fb_admins:
fb_app_id:
